apiVersion: v1
kind: Service
metadata:
  name: {{ include "tftp-server.fullname" . }}
  labels:
    component: tftp-server
spec:
  type: {{ .Values.service_type }}
  ports:
    - name: tftp
      port: {{ .Values.container_port }}
      targetPort: {{ .Values.container_port }}
      nodePort: {{ .Values.node_port }}
      protocol: UDP
  selector:
    matchLabels:
      component: tftp-server
